add do...catch...finally
egormanga/PySlang pull request #1
Opened 2024-11-21 19:48 UTC by BasedUser

nuff said

2024-11-21 20:01 UTC, egormanga requested changes
LGTM! Thank you.

Still needs to be tested and properly implemented in the AST and at least one of the compilers to be merged.

2024-11-21 20:01 UTC, egormanga commented on Slang.sldef
> +finallyclause: 'finally' block
These two are non-final.

2024-11-21 20:01 UTC, egormanga commented on Slang.sldef
> +docall: 'do' block catchclause* finallyclause?
This needs to be added to `statement`s.

2024-11-21 20:01 UTC, egormanga commented on Slang.sldef
> +resume: 'resume'
Please add these to `keywordexpr` as well.

2024-11-21 20:25 UTC, egormanga requested changes
LGTM, waiting for the AST part.

2024-11-21 22:41 UTC, BasedUser commented
note: untested as of yet

2024-11-21 23:03 UTC, egormanga requested changes
Does it actually parse? Maybe add a test for that.

2024-11-21 23:33 UTC, egormanga requested changes

2024-11-21 23:33 UTC, egormanga commented on ast.py
> +		return f"{self.finally_} {self.block}"
Actually, no space before the block is required.

2024-11-21 23:33 UTC, egormanga commented on ast.py
> +		return f"""{self.do_} {self.block}{f" {S(' ').join(self.catch)}" if (self.catch) else ''}{f" {self.finally_}" if (self.finally_) else ''}"""
ditto

2024-11-23 06:07 UTC, egormanga approved these changes

2024-11-23 06:25 UTC, merged